apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: open-data-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: ['sh', '-c', "until nc -z postgres 5432; do echo waiting for db; sleep 2; done"]
        - name: data-load
          image: data_load:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: "postgres"
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
            - name: reports-volume
              mountPath: /app/reports
            - name: plots-volume
              mountPath: /app/plots
        - name: data-quality
          image: data_quality_analysis:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: reports-volume
              mountPath: /app/reports
        - name: data-research
          image: data_research:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: reports-volume
              mountPath: /app/reports
        - name: visualization
          image: visualization:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: plots-volume
              mountPath: /app/plots
      containers:
        - name: web
          image: web:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
            - containerPort: 8000
          volumeMounts:
            - name: reports-volume
              mountPath: /app/reports
            - name: plots-volume
              mountPath: /app/plots
      volumes:
        - name: data-volume
          emptyDir: {}
        - name: reports-volume
          emptyDir: {}
        - name: plots-volume
          emptyDir: {}
