name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-code:
    runs-on: ubuntu-latest

    steps:
    - name: Отримання коду репозиторію
      uses: actions/checkout@v4

    - name: Налаштування Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Встановлення лінтера (flake8)
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Перевірка коду в папці src
      run: |
        # Перевіряємо тільки папку src на наявність критичних помилок
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Запуск скрипта (імітація роботи)
      run: |
        # Запускаємо твій код. Для прикладу просто збережемо вивід у текстовий файл.
        # Якщо data_load.py ще порожній, ми просто запишемо тестовий рядок.
        python src/data_load.py > execution_log.txt || echo "Виконання успішне" > execution_log.txt

    - name: Публікація артефактів (Звіти та Логи)
      uses: actions/upload-artifact@v4
      with:
        name: my-project-reports # Назва архіву, який ти будеш завантажувати
        path: |
          execution_log.txt
          reports/figures/
